title:              Mr.X's Blog
email:              2254750892@qq.com
description:        建议使用电脑版以获得最佳阅览体验（页面比例100%最佳）
author:             Mrx
baseurl:            "" # 如果是 username.github.io 则留空；否则写 /仓库名
url:                "https://marx2001.github.io"

# Social Profiles
github_username:    marx2001

# Add your google-analytics ID here to activate google analytics
# google_analytics:   UA-XXXXXXXXX-X

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

