title:              Mr.X's Blog
email:              2254750892@qq.com
description:        建议使用电脑版以获得最佳阅览体验（页面比例100%最佳）
author:             Mrx
baseurl:            ""
url:                "https://marx2001.github.io"

# Social Profiles
github_username:    marx2001

# Build settings
markdown:           kramdown

plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-sitemap

pagination:
  enabled: true
  per_page: 5
  permalink: "/page:num/"
  sort_reverse: true

autopages:
  enabled: true
  categories:
    enabled: true
    layouts:
      - autopage_category.html
    title: ":cat"
    permalink: "/:cat/"
    slugify:
      mode: "default"
      case: false
  tags:
    enabled: false
  collections:
    enabled: false