from pathlib import Path
import re

# ============================================================
# 0) 当前脚本所在目录
# ============================================================
workdir = Path(__file__).resolve().parent

# ============================================================
# 1) 查找所有 wannier90*.dat 文件
# ============================================================
dat_files = sorted(workdir.glob("wannier90*.dat"))

if not dat_files:
    print("No wannier90*.dat files found.")
    raise SystemExit

print(f"Found {len(dat_files)} file(s):")
for f in dat_files:
    print("  -", f.name)

# ============================================================
# 2) 逐个文件清洗并直接保存（覆盖原文件）
# ============================================================
for infile in dat_files:
    print(f"\nProcessing: {infile.name}")

    try:
        # 读取源文件内容
        text = infile.read_text(encoding="utf-8")

        # 1) 去掉 Mathematica 的"续行符"：反斜杠 + 换行
        text = re.sub(r"\\\s*\n", " ", text)

        # 2) 把字符串里的 \n 还原成真正换行，并移除引号
        text = text.replace("\\n", "\n")
        text = text.replace('"', '')  # 移除引号

        # 3) 压缩多余空格（>=2 个压成 1 个）
        text = re.sub(r"[ \t]{2,}", " ", text)

        # 4) 去掉包含"Generated by MagneticTB"的行
        lines = []
        for line in text.splitlines():
            if "Generated by MagneticTB" not in line:
                lines.append(line)

        # 5) 去掉空行 + 行尾空格
        lines = [line.rstrip() for line in lines if line.strip()]

        # 直接覆盖保存到原文件（不修改文件名）
        infile.write_text("\n".join(lines) + "\n", encoding="utf-8")

        print(f"  [OK] Saved: {infile.name}")

    except Exception as e:
        print(f"  [ERROR] Failed to process {infile.name}: {str(e)}")

print(f"\nAll operations completed. Total files processed: {len(dat_files)}")